{
  "sequenceId": "group_133",
  "name": "Subflow 133",
  "description": "A group of related nodes",
  "messages": [
    {
      "id": 1,
      "type": "autoroute",
      "routes": [
        {
          "condition": "task.previousStatus == 'pending'",
          "nextMessageId": 87
        },
        {
          "condition": "task.previousStatus == 'failed'",
          "nextMessageId": 79
        }
      ]
    },
    {
      "id": 79,
      "contentKey": "bot.react.task_failure.supportive",
      "text": "Uh oh... Looks like you never cleared your last deadline...|||Hopefully it won't happen again",
      "nextMessageId": 80
    },
    {
      "id": 80,
      "type": "dataAction",
      "dataActions": [
        {
          "type": "reset",
          "key": "task.previousStatus",
          "value": ""
        }
      ],
      "sequenceId": "group_131"
    },
    {
      "id": 87,
      "contentKey": "bot.request.task_status.gentle",
      "text": "Ok, so did you manage to do your thing last time?",
      "nextMessageId": 88
    },
    {
      "id": 88,
      "type": "choice",
      "choices": [
        {
          "text": "As a matter of fact, I did!",
          "contentKey": "user.choose.task_status.completed",
          "nextMessageId": 89
        },
        {
          "text": "I... Did not...",
          "contentKey": "user.choose.task_status.failed",
          "nextMessageId": 90
        }
      ]
    },
    {
      "id": 89,
      "contentKey": "bot.acknowledge.completion.positive",
      "text": "Atta boy",
      "sequenceId": "group_145"
    },
    {
      "id": 90,
      "contentKey": "bot.acknowledge.failure.supportive",
      "text": "Well, can't say I'm surprised...",
      "sequenceId": "group_131"
    }
  ]
}